### ISSUE TITLE
H calculation for pose_measurement

### ISSUE THREAD

**Issue by prclibo** [ethz-asl/ethzasl_msf#106]
According to https://github.com/ethz-asl/ethzasl_msf/blob/master/msf_updates/include/msf_updates/pose_sensor_handler/pose_measurement.h#L304, the position residual is denoted as:

    r = z_p - C_wv * (-p_wv + p + C_q * p_ic) * lambda

[L242](https://github.com/ethz-asl/ethzasl_msf/blob/master/msf_updates/include/msf_updates/pose_sensor_handler/pose_measurement.h#L242) differentiates the residual against `q_wv` as:

    -C_wv * [p + C_q * p_ic]_x * lambda

which I think misses `-p_wv` inside `[*]_x`.

**Comment by simonlynen** [comment]
@prclibo yes it looks like skew_old was not updated when ```p_wv``` was introduced (my bad). Thanks for catching this. Would you mind making a pull-request for this change?
