### ISSUE TITLE
[Q] Possibility of integrating two Pose sensors?

### ISSUE THREAD

**Issue by cynosure4sure** [ethz-asl/ethzasl_msf#157]
I was wondering if there is a possibility of using two Pose sensors in the current form of the framework. I tried creating a dual pose sensor file but there was a conflict with both sensors trying to access the same sensor. Should I first create another sensor with different variable names? Any help proceeding in this regard will be appreciated.

Thank you.

**Comment by tdnet12434** [comment]
You can catch up the solution from this issue.
https://github.com/ethz-asl/ethzasl_msf/issues/80
