### ISSUE TITLE
How to integrate this framework with self-made multirotor?

### ISSUE THREAD

**Issue by fboris** [ethz-asl/ethzasl_msf#54]
Hi all,
After I read the tutorial on the ROS ethzasl_sensor_fusion wiki, I have a brief overview. Here is my goal - let my miltirotor could fly indoor enviroment(You can see more information [here](https://github.com/moon-bear/QuadcopterFlightControl)). In this [thread](https://github.com/ethz-asl/ethzasl_sensor_fusion/issues/5), Stephan said old ethzasl_sensor_fusion is possible to integrate without asctec helicopters. But something I'm trying to figure out. 

1)I want to integrate ethzasl_ptam(visual slam 6 DOF) and pressure sensor(1DOF)with my multirotor. Which launch file closes to my scenario?

2)relate with question 1. I found this launch file(pose_pressure_sensor.launch) very close to my scenario, but I'm not very sure. I have a look at this launch file and its rosparam file(position_sensor_fix.yaml). In ths position_sensor_fix.yaml:
```
core/core_noise_acc: 0.083
core/core_noise_accbias: 0.0083
core/core_noise_gyr: 0.0013
core/core_noise_gyrbias: 0.00013
```
Are these bias represtented the ekf initial state? 

3)This ROS package(ethzasl_msf) need the dependency [asctec_mav_framework](https://github.com/ethz-asl/asctec_mav_framework). Is there any way to remove it? Since we do not have any asctec mavs.

4)The data rate of any sensor. Does this framework have some limitation of sensor data rate? Because discrete kalman filter timing is critical, I assume this framework act like old ethzasl_sensor_fusion. As tutorial mentioned, Prediction(or call propagation) is continously base on IMU and update measurement is done in lower speed(ptam is 20hz).

Thanks for reading this long question. I'm glad you open this framework for whom are working on sensor fusion research.

FBoris

**Comment by simonlynen** [comment]
For future ref, we have a proper documentation of this here: https://github.com/ethz-asl/ethzasl_msf/issues/90
