### ISSUE TITLE
Glog library not found

### ISSUE THREAD

**Issue by mfaessle** [ethz-asl/ethzasl_msf#62]
I cloned the repository today and tried to compile it on ubuntu 12.04 and 13.10 and I got the same error on both stating:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLOG_LIBRARY (ADVANCED)
    linked by target "test_similaritytransform" in directory [...]
    linked by target "test_static_statelist" in directory [...]

How do I get glog to be installed and found properly?

Thanks for your help

**Comment by simonlynen** [comment]
Assuming this is resolved.
