### ISSUE TITLE
Integrating onboard MAV with multiple sensors sources

### ISSUE THREAD

**Issue by mhkabir** [ethz-asl/ethzasl_msf#69]
OK, so I've been reading up on whatever I've been able to find on your framework. I would like to thank you guys for the amazing job you've done and for keeping this framework updated.

I'm working on a small quadrotor which should be able to transition seamlessly from indoor to outdoor environments and switch between sensor sources depending on availability/data quality. I have the following sensors onboard : 9DOF IMU (MPU 6000 accel-gyro + HMC5883L magneto), Baro (MS5611), GPS, Forward facing monocular camera (for PTAM), Downward facing optical flow camera (PX4Flow) and downward pointing Sonar/Laser rangefinder.

Now, the PTAM and IMU data can be used anywhere, but the GPS, optical flow, barometer and sonar availability changes with outdoor <> indoor transition and altitude above ground.

My questions might sound a bit noobish, but please bear with me.

1. Does the present IMU implementation take into account the magnetometer data? Fusing the mag would improve PTAM's yaw drift I think?
2. Does this framework output a pose estimate which is then fed into the flight controller's position controller? Or does it output a final attitude + positon? Would this mean that absolutely no sensor fusion would be done on the low level FC? 
3. I am using an Odroid U3 at the moment for running ROS. Would this be enough computational power or should I try and get hold of a Intel board or similar?
4. Is the global position and local position transition handled already in the framework? Could we keep an approximate global estimate from the last good GPS fix before transitioning to local sensors?
5. I read in your IROS 2013 paper that you had flown trajectories at 4m/s. How were you handling the navigation?
6. In my FC, any position data (GPS/optical flow) is fused with inertial data  before being passed onto the controllers to improve performance. How would this be handled if I use this framework? 

I'm sure that I will have more questions in the future about getting this fully integrated onboard so please keep this issue open. THANKS!!

Also, I'd just like you guys to know that I'm not affiliated to any college / university. I'm just a 16 year old student with a crazy interest in MAVs. 

Kabir

**Comment by simonlynen** [comment]
Assuming this is resolved.
