### ISSUE TITLE
delay and pose sensor setup

### ISSUE THREAD

**Issue by fboris** [ethz-asl/ethzasl_msf#71]
hi guys,
When I was using pose_sensor.launch as my launch file, I found I always got these message. I'm using imu(very poor imu MPU9250) at 800hz with [svo](https://github.com/uzh-rpg/rpg_svo) at 60hz.
```
[ WARN] [1403628860.088846747]: msf_core: imu message drop curr seq:44574 expected: 44561
[ WARN] [1403628860.089542803]: You tried to give me a measurement which is too far in the past. Are you sure your clocks are synced and delays compensated correctly? [measurement: 8859.94 (s) first state in buffer: 8859.96 (s)]
```
My question is how to set the delay correctly?

Sometime, the fuzzy tracking had been triggered. Then, the filter went to diverge. I refer the fuzzy tracking that mentioned by @simonlynen (https://github.com/ethz-asl/ethzasl_sensor_fusion/issues/20). I checked my quaternion of camera w.r.t imu. It is my opinion: If I set some rotation wrong, it could triggered the *fuzzy tracking* to the end. But It did not happen. I'm not sure these two issue are related.

Last question, are these two values for pose sensor translation and rotation noise configuration?
in pose_sensor.launch
```
pose_sensor/pose_noise_meas_p: 0.02
pose_sensor/pose_noise_meas_q: 0.02
```

**Comment by simonlynen** [comment]
Assuming this is resolved.
