### ISSUE TITLE
GPS reference frame and position_init_yaw

### ISSUE THREAD

**Issue by blackistheanswer** [ethz-asl/ethzasl_msf#78]
Hi guys, congratulation for the great job with this framework and thank you for having decided to share it.
Right now I am trying to implement a basic GPS+IMU configuration (this should be the first step towards a more complex IMU+GPS+Compass+Vision implementation).
I'm getting a little confused by the reference you use for the GPS. Looking at the code I think you convert the standard Lat Lon Alt data in ECEF frame, but I don't understand how should I set the 'position_yaw_init' parameter.
Has this to be set with respect to the ECEF frame or to the North (as it would be measured by a compass)?
Also, with respect to which frame/origin is the fused position from '/msf_core/state_out' expressed when using GPS?

**Comment by simonlynen** [comment]
Assuming this is resolved.
