### ISSUE TITLE
Accelerometer aiding 

### ISSUE THREAD

**Issue by nplayle** [ethz-asl/ethzasl_msf#86]
Hi, 

I'm currently using MSF with ETHZ PTAM in a masters project and have a few questions. 

#### Are the accelerometers used in the determination of pitch and roll?
- Currently I cannot see anywhere this is the case. Is the angle estimate corrected towards the estimate coming from PTAM? I am not 100% sure that my current setup of PTAM is estimating attitude correctly, especially if the initial coordinate frame of PTAM is not gravity aligned. If not, based on the MSF framework it doesnt look like accel aiding would be too difficult to implement? 
I believe my inaccurate angle estimates from PTAM might be incorrectly estimating accelerometer and gyro biases causing me to read incorrect velocity estimates if I pitch / roll my setup. 

#### What corrects the orientation estimate in the case of GNSS only? 
- if PTAM is not available then there are no angle measurements available to correct the gyro based estimates (based on my current understanding)

#### What units is the pressure input? 
- In pose_pressure_sensor there looks to be a pressure sensor used, but I can't find anywhere that suggests the scale. Is it already computed into metres?

Thanks!
Nick

**Comment by simonlynen** [comment]
Assuming this is clarified.
