### ISSUE TITLE
Magnetometer integration

### ISSUE THREAD

**Issue by blackistheanswer** [ethz-asl/ethzasl_msf#87]
Hi,

I am working in order to add full magnetometer support to the msf framework. I am trying to follow the approach described in Weiss' PhD thesis (chapter 3) and in the vismaggps branch of this repository (https://github.com/ethz-asl/ethzasl_msf/tree/vismaggps/vismaggps_fusion). Therefore I added three states to the state vector:

- qm_i:	magnetometer - imu rotation quaternion
- alpha:	(elevation) angle of the magnetic vector
- beta:	(azimuth) angle of the magnetic vector

Since the coding part is almost over I would like to start with some testing in this days, but I still would like to ask you some questions/confirmations about the approach:

**qm_i, alpha and beta process noises**
I think it is correct to model these auxiliary states as noise-free (Weiss, page 91). Is it ok?

**alpha and beta init**
If I've understood correctly I have to initialize the alpha (elevation) angle with the "inclination" value that can be found, for example, here: http://magnetic-declination.com/. 
For Zurich the value is 63° 18' (i.e. 1.1 rads) but in the vismaggps code the value is initialized to -1.1 (https://github.com/ethz-asl/ethzasl_msf/blob/vismaggps/vismaggps_fusion/src/vismaggps_measurements.h#L77). I think this is due to some reference system adjustment for your setup. Can you confirm this ?
Also, what about the beta angle? Can I fix it to an arbitrary value (e.g. 0) ?

**Noise settings in Dynamic Reconfigure tool**
I don't understand the convention chosen for the noise representation in the ROS Dynamic Reconfigure tool and in .yaml files.
It seems from https://github.com/ethz-asl/ethzasl_msf/issues/54#issuecomment-39201379 that I should use the continuos time noise densities; but in the .cfg files it seems I should use directly the standard deviation (e.g. "noise for measurement sensor (**std. dev**)" in https://github.com/ethz-asl/ethzasl_msf/blob/master/msf_updates/cfg/PositionPoseSensor.cfg#L55 )

Thanks

**Comment by simonlynen** [comment]
Assuming this is resolved.
