### ISSUE TITLE
Noise Spectral Densities 

### ISSUE THREAD

**Issue by blackistheanswer** [ethz-asl/ethzasl_msf#88]
Hi guys,
I've a few questions about getting the right Noise Spectral Densities from the datasheets.

**Noise Spectral Densities**

For my tests I am currently using a Pixhawk and its MPU6000 IMU. 
The datasheet for this sensor gives:

`accNSD = 0.0392  m/s^2/sqrt(Hz)`
`gyrNSD = 0.03142  °/s/sqrt(Hz)`

Both the values refer to a cut off frequency of the internal Low Pass Filter of 10Hz 
But in my case the LPF is set to cut at 42Hz. Assuming the ideal white Gaussian noise case, the NSD is constant along the frequencies spectrum; is it therefore safe to assume the updated densities to be:

`accNSD' = accNSD*4.2`
`gyrNSD' = gyrNSD*4.2`

????

**Magnetometer Noise Floor parameter**

The only noise related parameter, from the datasheet of the magnetometer I am using (HMC5883L), is 

`Noise Floor (NF) = 2 mG (standard deviation 100 samples)`

Following the same approach described in this video https://www.youtube.com/watch?v=ywChrIRIXWQ I would compute the NSD as 

`magNSD = NF / sqrt(f)`

Would you suggest to do the same ?

**Experimental Noise Spectral Density characterization**

Do you have some references/application notes about experimental characterization of the NSD ?
I tried to apply the same approach of the cited video for acc and gyr NSDs (adjusting the LowPass Filter frequency of the sensor to 10Hz)  but it resulted in results very different from the ones on the datasheet listed in question 1).

**Comment by simonlynen** [comment]
Please see #90
